config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :committees
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'events#index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/club.rb
class Club < ApplicationRecord
end

app/models/committee.rb
class Committee < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/event.rb
class Event < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.where('occur_at > ?', Time.now).order(occur_at: :desc)
  end

  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/index.html.erb
<div class="container">
  <h1>Campus Events</h1>
  <hr>
  <div class="row">
    <% @events.each do |event| %>
      <div class="col-sm col-md-6 col-lg-4">
        <div class="card">
          <div class="card-body">
            <h3 class="card-title"><%= event.title %></h3>
            <%= simple_format event.description %>
            <p><%= event.occur_at %></p>
            <a href="#" class="btn btn-primary">More info</a>
          </div>
        </div>
      </div>
    <% end %>  
  </div>
  <hr>
  <footer>
    <%= link_to 'Committee Sign In', new_committee_session_path %>
  </footer>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CampusCalendar</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>
    <%= yield %>
  </body>
</html>